
### List all games
GET http://localhost:8000/api/games

### Get game status
GET http://localhost:8000/api/games/74b72b23-8c80-4ccd-b83c-cf391426249b

### Create a new game
POST http://localhost:8000/api/games
Content-Type: application/json

{
  "name": "First game",
  "creatorId": 1,
  "targetScore": 500,
  "cardsPerPlayer": 7
}

### Create another game
POST http://localhost:8000/api/games
Content-Type: application/json

{
  "name": "Another game",
  "creatorId": 2,
  "targetScore": 50,
  "cardsPerPlayer": 2
}


### Join a game (replace {{gameId}})
POST http://localhost:8000/api/games/9af4b7b7-0fea-4d1e-8b6d-0a84934b6645/join
Content-Type: application/json

{
  "userId": 3
}

### Join a game again (should fail if user is already in the game)
POST http://localhost:8000/api/games/9af4b7b7-0fea-4d1e-8b6d-0a84934b6645/join
Content-Type: application/json

{
  "userId": 3
}

### Leave a game (replace {{gameId}})
POST http://localhost:8000/api/games/99a4cd34-74b9-44d7-8294-892318248c07/leave
Content-Type: application/json

{
  "userId": 7
}

### Start a game (replace {{gameId}})
POST http://localhost:8000/api/games/9af4b7b7-0fea-4d1e-8b6d-0a84934b6645/start

### Delete a game (replace {{gameId}})
DELETE http://localhost:8000/api/games/9af4b7b7-0fea-4d1e-8b6d-0a84934b6645

